function report = ECMS_DIAGNOSE()
%ECMS_DIAGNOSE Verify that MATLAB Online resolves one complete ECMS VPP package.
% This diagnostic is read-only. It never calls the legacy 6.6 kV model and
% never modifies A settings, M links, generated runs or MATLAB preferences.

packageRoot = fileparts(mfilename("fullpath"));
matlabDir = fullfile(packageRoot,"matlab");

requiredFiles = [ ...
    "ECMSVPP.m"; ...
    "ECMS_START.m"; ...
    "ECMS_RUN.m"; ...
    "ECMS_RESULT.m"; ...
    "ECMS_SELF_TEST.m"; ...
    "matlab/triplens_ecms_vpp_editor.m"; ...
    "matlab/triplens_ecms_editor.m"; ...
    "matlab/triplens_ecms_vpp_simulate.m"; ...
    "matlab/run_cloud_result.m"; ...
    "config/ecms_a_settings.csv"; ...
    "config/ecms_a_equipment.csv"; ...
    "config/ecms_command_catalog.csv"; ...
    "config/fault_presets.json"; ...
    "config/vpp_baseline_v1.json"; ...
    "config/common_trip_matrix.csv"; ...
    "config/tag_alias_contract.csv"; ...
    "config/dcs_alarm_rules.csv"; ...
    "data/ecms_m_links.csv"; ...
    "data/thermo_vpp_m_locked_tags.csv"; ...
    "topology/triplens_ecms_vpp.svg"; ...
    "topology/triplens_ecms_6p9kv.svg"];

missingFiles = strings(0,1);
for index = 1:numel(requiredFiles)
    if ~isfile(fullfile(packageRoot,requiredFiles(index)))
        missingFiles(end+1,1) = requiredFiles(index); %#ok<AGROW>
    end
end
assert(isempty(missingFiles),"TripLens:IncompletePackage", ...
    "ECMS VPP package is incomplete. Missing:\n%s",join(missingFiles,newline));

addpath(matlabDir,"-begin");
rehash;
clear triplens_ecms_vpp_editor triplens_ecms_vpp_simulate run_cloud_result;

functionNames = ["triplens_ecms_vpp_editor";"triplens_ecms_vpp_simulate";"run_cloud_result"];
expectedFiles = [ ...
    fullfile(matlabDir,"triplens_ecms_vpp_editor.m"); ...
    fullfile(matlabDir,"triplens_ecms_vpp_simulate.m"); ...
    fullfile(matlabDir,"run_cloud_result.m")];
resolvedFiles = strings(size(functionNames));
for index = 1:numel(functionNames)
    resolvedFiles(index) = string(which(functionNames(index)));
    assert(resolvedFiles(index)==string(expectedFiles(index)), ...
        "TripLens:PathShadowing", ...
        "Wrong %s is on the MATLAB path.\nExpected: %s\nResolved: %s", ...
        functionNames(index),expectedFiles(index),resolvedFiles(index));
end

settingsPath = fullfile(packageRoot,"config","ecms_a_settings.csv");
settings = readtable(settingsPath,"Delimiter",",","ReadVariableNames",true, ...
    "VariableNamingRule","preserve","TextType","string");
requiredSettingColumns = ["setting_id","value","unit","status"];
assert(all(ismember(requiredSettingColumns,string(settings.Properties.VariableNames))), ...
    "TripLens:InvalidASettings","A settings CSV header is invalid.");
auxRow = settings(settings.setting_id=="AUX_BUS_VOLTAGE_KV",:);
assert(height(auxRow)==1 && str2double(string(auxRow.value(1)))==6.9, ...
    "TripLens:WrongTopologyVoltage","This package requires one 6.9 kV auxiliary-bus setting.");

editorText = string(fileread(fullfile(matlabDir,"triplens_ecms_vpp_editor.m")));
viewerText = string(fileread(fullfile(matlabDir,"run_cloud_result.m")));
engineText = string(fileread(fullfile(matlabDir,"triplens_ecms_vpp_simulate.m")));
combinedText = editorText + newline + viewerText + newline + engineText;
assert(~contains(combinedText,"start_here"),"TripLens:LegacyFallback", ...
    "A legacy start_here fallback was found in the authoritative ECMS VPP package.");
assert(~contains(upper(combinedText),"SST-A") && ~contains(upper(combinedText),"SST-B"), ...
    "TripLens:LegacySST","Obsolete SST topology text was found in the 6.9 kV/no-SST package.");

report = struct();
report.Pass = true;
report.PackageRoot = string(packageRoot);
report.RequiredFileCount = numel(requiredFiles);
report.FunctionNames = functionNames;
report.ResolvedFiles = resolvedFiles;
report.AuxiliaryBusVoltageKV = 6.9;
report.Topology = "GT/ST main-transformer reverse receiving; no separate SST";

fprintf("PASS: ECMS VPP package diagnostics completed.\n");
fprintf("      Root: %s\n",packageRoot);
fprintf("      Files: %d required files present\n",numel(requiredFiles));
fprintf("      Topology: 6.9 kV / no SST / unique function paths\n");
end
