function report = ECMS_SELF_TEST()
%ECMS_SELF_TEST Verify the MATLAB-native ECMS VPP without external tools.

packageRoot = fileparts(mfilename("fullpath"));
matlabDir = fullfile(packageRoot,"matlab");
addpath(matlabDir,"-begin");
clear triplens_ecms_vpp_simulate;
rehash;
engineFile = fullfile(matlabDir,"triplens_ecms_vpp_simulate.m");
resolvedEngine = string(which("triplens_ecms_vpp_simulate"));
assert(resolvedEngine==string(engineFile), ...
    "TripLens:WrongNativeEngine", ...
    "Wrong native ECMS engine is on the path. Expected %s, resolved %s", ...
    engineFile,resolvedEngine);

checks = strings(0,1);
temporaryOutputRoot = tempname;
mkdir(temporaryOutputRoot);
temporaryCleanup = onCleanup(@() cleanupSelfTestFolder(temporaryOutputRoot)); %#ok<NASGU>
normal = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot, ...
    "TripTime",0.5,"StopTime",2.0,"FaultPreset","none");
assert(isfolder(normal.RunFolder),"Normal run folder was not created.");
assert(all(isfile(fullfile(normal.RunFolder,["processbus.csv","ecms-trend.csv", ...
    "ecms-events.csv","ecms-feeders.csv","manifest.json"]))), ...
    "Normal run is incomplete.");
assert(all(normal.ECMSTrend.bus_a_voltage_kv==6.9), ...
    "Normal BUS-A must remain energized at 6.9 kV by reverse feed.");
assert(~any(contains(lower(string(normal.ECMSTrend.Properties.VariableNames)),"sst")), ...
    "SST must not exist in the authoritative topology.");
assert(normal.Manifest.runtime.thermosyspro_used==false, ...
    "Fallback manifest must not claim ThermoSysPro provenance.");
normalPeriodMs = str2double(string(normal.Settings.value( ...
    string(normal.Settings.setting_id)=="TREND_PERIOD_MS")));
expectedNormalGrid = (0:normalPeriodMs:2000).';
assert(isequal(normal.ECMSTrend.source_time_ms,expectedNormalGrid), ...
    "The default standard sampling profile changed its legacy uniform grid.");
assert(all(normal.ECMSTrend.sampling_resolution== ...
    "NORMAL_"+string(normalPeriodMs)+"MS"), ...
    "Standard rows must declare the configured normal sampling resolution.");
assert(string(normal.Manifest.sampling.profile)=="standard", ...
    "The default manifest must declare the standard sampling profile.");
checks(end+1) = "normal atomic run / 6.9 kV / no SST";

gridLoss = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot, ...
    "TripTime",0.5,"StopTime",2.0,"FaultPreset","grid_loss");
settled = gridLoss.ECMSTrend.source_time_ms>=1500;
assert(any(settled) && all(gridLoss.ECMSTrend.bus_a_voltage_kv(settled)==0), ...
    "Grid-loss run must remove GT-path reverse feed.");
checks(end+1) = "grid-loss fault propagation";

commands = table([0.6;0.8;1.0;1.2;1.3;1.4], ...
    ["FWP-HP";"FWP-HP";"FWP-HP";"FWP-HP";"VCB-A01";"FWP-HP"], ...
    ["STOP";"START";"TRIP";"RESET";"CLOSE";"START"], ...
    'VariableNames',{'time_s','equipment_id','command'});
commandRun = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot, ...
    "TripTime",0.5,"StopTime",2.0,"CommandTable",commands);
hpRows = commandRun.ECMSFeeders.equipment_id=="FWP-HP";
row600 = hpRows & commandRun.ECMSFeeders.source_time_ms==600;
row800 = hpRows & commandRun.ECMSFeeders.source_time_ms==800;
row1000 = hpRows & commandRun.ECMSFeeders.source_time_ms==1000;
row1080 = hpRows & commandRun.ECMSFeeders.source_time_ms==1080;
row1200 = hpRows & commandRun.ECMSFeeders.source_time_ms==1200;
row1300 = hpRows & commandRun.ECMSFeeders.source_time_ms==1300;
row1400 = hpRows & commandRun.ECMSFeeders.source_time_ms==1400;
assert(commandRun.ECMSFeeders.breaker_closed(row600)==1 && ...
    commandRun.ECMSFeeders.run_enable(row600)==0 && ...
    commandRun.ECMSFeeders.breaker_closed(row800)==1 && ...
    commandRun.ECMSFeeders.run_enable(row800)==1, ...
    "FWP STOP/START must change only the run command while VCB remains closed.");
assert(commandRun.ECMSFeeders.breaker_closed(row1000)==1 && ...
    commandRun.ECMSFeeders.trip_latched(row1000)==1 && ...
    commandRun.ECMSFeeders.breaker_closed(row1080)==0, ...
    "FWP Trip must latch immediately and open the VCB after 80 ms.");
assert(commandRun.ECMSFeeders.trip_latched(row1200)==0 && ...
    commandRun.ECMSFeeders.breaker_closed(row1200)==0 && ...
    commandRun.ECMSFeeders.breaker_closed(row1300)==1 && ...
    commandRun.ECMSFeeders.run_enable(row1400)==1, ...
    "RESET must not reclose; VCB CLOSE then FWP START must be explicit.");
assert(any(commandRun.ECMSEvents.tag=="COMMAND.FWP-HP.TRIP"), ...
    "Command audit event is missing.");
checks(end+1) = "FWP STOP/TRIP/RESET/VCB CLOSE state machine / audit event";

feederFault = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot,"TripTime",0.5,"StopTime",1.2, ...
    "FaultPreset","fwp_hp_feeder_fault");
faultEvents = feederFault.ECMSEvents;
assert(any(faultEvents.tag=="50FWP-HP.OPERATE" & ...
    faultEvents.source_time_ms==515) && ...
    any(faultEvents.tag=="VCB-A01.CLOSED" & ...
    faultEvents.source_time_ms==595), ...
    "Provisional feeder 50 protection timing did not reach the VCB.");
faultAt500 = feederFault.ECMSFeeders.equipment_id=="FWP-HP" & ...
    feederFault.ECMSFeeders.source_time_ms==500;
faultAt600 = feederFault.ECMSFeeders.equipment_id=="FWP-HP" & ...
    feederFault.ECMSFeeders.source_time_ms==600;
assert(str2double(feederFault.ECMSFeeders.fault_current_a(faultAt500))==12000 && ...
    feederFault.ECMSFeeders.breaker_closed(faultAt600)==0, ...
    "Provisional RMS feeder fault current was not interrupted by VCB opening.");
checks(end+1) = "provisional RMS 50/51 feeder protection / VCB interruption";

zeroDelaySettings = normal.Settings;
zeroDelayIds = upper(strtrim(string(zeroDelaySettings.setting_id)));
zeroDelayRows = ismember(zeroDelayIds,["TRIP_RECEIVE_DELAY_MS", ...
    "LOCKOUT_OPERATE_DELAY_MS","GT_BREAKER_OPEN_DELAY_MS"]);
zeroDelaySettings = setSelfTestSettingValues(zeroDelaySettings,zeroDelayRows,0);
zeroDelay = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot,"SettingsTable",zeroDelaySettings, ...
    "TripTime",0.5,"StopTime",1.0);
sameTimeTags = zeroDelay.ECMSEvents.tag( ...
    zeroDelay.ECMSEvents.source_time_ms==500);
causalTags = ["GT.TRIP.CMD";"86GT.TRIP.RECEIVED";"86GT.OPERATE"; ...
    "52GT.CLOSED";"TR-GT.DIRECTION"];
sameTimeTags = sameTimeTags(ismember(sameTimeTags,causalTags));
assert(isequal(sameTimeTags,causalTags), ...
    "Equal-time protection events must retain causal insertion order.");
checks(end+1) = "equal-time GT protection causal order";

incidentSettings = normal.Settings;
settingIds = upper(strtrim(string(incidentSettings.setting_id)));
incidentSettings = setSelfTestSettingValues(incidentSettings, ...
    settingIds=="AUTO_BUS_TIE_TRANSFER",1);
incident = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot,"SettingsTable",incidentSettings, ...
    "TripTime",0.5,"StopTime",1.2,"FaultPreset","uat_a_fault", ...
    "SamplingProfile","incident_1ms","IncidentPeriodMs",1, ...
    "IncidentPreMs",100,"IncidentPostMs",600);
incidentTimes = incident.ECMSTrend.source_time_ms;
assert(all(diff(incidentTimes)>0), ...
    "Incident sampling grid must be strictly increasing and duplicate-free.");
incidentWindow = incidentTimes>=400 & incidentTimes<=1100;
assert(all(diff(incidentTimes(incidentWindow))==1), ...
    "Incident window must contain a complete 1 ms grid.");
assert(all(incident.ECMSTrend.sampling_resolution(incidentWindow)=="INCIDENT_1MS"), ...
    "Incident-window rows must declare 1 ms sampling resolution.");
assert(all(incident.ECMSTrend.sampling_resolution(~incidentWindow)== ...
    "NORMAL_"+string(normalPeriodMs)+"MS"), ...
    "Rows outside the incident window must retain the normal trend period.");
row800 = incidentTimes==800;
row801 = incidentTimes==801;
assert(any(row800) && incident.ECMSTrend.cb_tie_ab_closed(row800)==0 && ...
    any(row801) && incident.ECMSTrend.cb_tie_ab_closed(row801)==1, ...
    "Automatic bus transfer must honor the 300 ms UV delay plus one actual sample.");
assert(string(incident.Manifest.sampling.profile)=="incident_1ms" && ...
    incident.Manifest.sampling.ecms.incident_period_ms==1 && ...
    incident.Manifest.sampling.ecms.incident_window_start_ms==400 && ...
    incident.Manifest.sampling.ecms.incident_window_end_ms==1100, ...
    "Incident sampling manifest is incomplete or incorrect.");
checks(end+1) = "incident 1 ms union grid / variable-period auto transfer";

% Exercise replacement of an already existing pointer without modifying the
% real package. This catches MATLAB Drive-style stale-tail concatenation.
pointerPackageRoot = fullfile(temporaryOutputRoot,"pointer_package");
mkdir(pointerPackageRoot);
copyfile(fullfile(packageRoot,"config"),fullfile(pointerPackageRoot,"config"));
copyfile(fullfile(packageRoot,"data"),fullfile(pointerPackageRoot,"data"));
copyfile(fullfile(packageRoot,"topology"),fullfile(pointerPackageRoot,"topology"));
triplens_ecms_vpp_simulate("PackageRoot",pointerPackageRoot, ...
    "TripTime",0.2,"StopTime",1.0);
pointerSecond = triplens_ecms_vpp_simulate("PackageRoot",pointerPackageRoot, ...
    "TripTime",0.2,"StopTime",1.0);
pointerText = strtrim(string(fileread(fullfile(pointerPackageRoot,"latest_run.txt"))));
expectedPointer = "runs/"+pointerSecond.RunId;
assert(pointerText==expectedPointer,"TripLens:PointerSelfTest", ...
    "latest_run.txt contains stale or concatenated bytes after replacement.");
assert(isfolder(fullfile(pointerPackageRoot,char(pointerText))), ...
    "TripLens:PointerSelfTest","latest_run.txt does not resolve to a run folder.");
checks(end+1) = "transactional latest-run pointer replacement";

report = struct("Passed",numel(checks),"Checks",checks, ...
    "RunIds",[normal.RunId;gridLoss.RunId;commandRun.RunId;feederFault.RunId; ...
    zeroDelay.RunId;incident.RunId], ...
    "TemporaryRunsRemovedOnReturn",true);
fprintf("PASS: ECMS_SELF_TEST %d/%d checks passed.\n",numel(checks),numel(checks));
disp(checks);
end

function cleanupSelfTestFolder(pathValue)
if isfolder(pathValue)
    rmdir(pathValue,"s");
end
end

function settings = setSelfTestSettingValues(settings,rows,numericValue)
if isnumeric(settings.value)
    settings.value(rows) = numericValue;
elseif iscell(settings.value)
    settings.value(rows) = repmat({char(string(numericValue))},nnz(rows),1);
else
    settings.value(rows) = string(numericValue);
end
end
