function report = ECMS_SELF_TEST()
%ECMS_SELF_TEST Verify the MATLAB-native ECMS VPP without external tools.

packageRoot = fileparts(mfilename("fullpath"));
matlabDir = fullfile(packageRoot,"matlab");
addpath(matlabDir,"-begin");
clear triplens_ecms_vpp_simulate;
rehash;
engineFile = fullfile(matlabDir,"triplens_ecms_vpp_simulate.m");
resolvedEngine = string(which("triplens_ecms_vpp_simulate"));
assert(resolvedEngine==string(engineFile), ...
    "TripLens:WrongNativeEngine", ...
    "Wrong native ECMS engine is on the path. Expected %s, resolved %s", ...
    engineFile,resolvedEngine);

checks = strings(0,1);
temporaryOutputRoot = tempname;
mkdir(temporaryOutputRoot);
temporaryCleanup = onCleanup(@() cleanupSelfTestFolder(temporaryOutputRoot)); %#ok<NASGU>
normal = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot, ...
    "TripTime",0.5,"StopTime",2.0,"FaultPreset","none");
assert(isfolder(normal.RunFolder),"Normal run folder was not created.");
assert(all(isfile(fullfile(normal.RunFolder,["processbus.csv","ecms-trend.csv", ...
    "ecms-events.csv","ecms-feeders.csv","manifest.json"]))), ...
    "Normal run is incomplete.");
assert(all(normal.ECMSTrend.bus_a_voltage_kv==6.9), ...
    "Normal BUS-A must remain energized at 6.9 kV by reverse feed.");
assert(~any(contains(lower(string(normal.ECMSTrend.Properties.VariableNames)),"sst")), ...
    "SST must not exist in the authoritative topology.");
assert(normal.Manifest.runtime.thermosyspro_used==false, ...
    "Fallback manifest must not claim ThermoSysPro provenance.");
checks(end+1) = "normal atomic run / 6.9 kV / no SST";

gridLoss = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot, ...
    "TripTime",0.5,"StopTime",2.0,"FaultPreset","grid_loss");
settled = gridLoss.ECMSTrend.source_time_ms>=1500;
assert(any(settled) && all(gridLoss.ECMSTrend.bus_a_voltage_kv(settled)==0), ...
    "Grid-loss run must remove GT-path reverse feed.");
checks(end+1) = "grid-loss fault propagation";

commands = table(1,1.0,"FWP-HP","HP feedwater pump","TRIP",0,"BOOL", ...
    "THERMO_ADAPTER_REQUIRED","FWP_HP_TRIP","TSP.DRUM.HP.FW_FLOW","QUEUED", ...
    "self-test",'VariableNames',{'sequence','time_s','equipment_id', ...
    'equipment_label','command','command_value','unit','execution_layer', ...
    'model_input','feedback_tag','status','note'});
commandRun = triplens_ecms_vpp_simulate("PackageRoot",packageRoot, ...
    "OutputRoot",temporaryOutputRoot, ...
    "TripTime",0.5,"StopTime",2.0,"CommandTable",commands);
rows = commandRun.ECMSFeeders.equipment_id=="FWP-HP" & ...
    commandRun.ECMSFeeders.source_time_ms>=1200;
assert(any(rows) && all(commandRun.ECMSFeeders.breaker_closed(rows)==0), ...
    "FWP-HP TRIP command did not open the configured feeder.");
assert(any(commandRun.ECMSEvents.tag=="COMMAND.FWP-HP.TRIP"), ...
    "Command audit event is missing.");
checks(end+1) = "live command table / feeder state / audit event";

% Exercise replacement of an already existing pointer without modifying the
% real package. This catches MATLAB Drive-style stale-tail concatenation.
pointerPackageRoot = fullfile(temporaryOutputRoot,"pointer_package");
mkdir(pointerPackageRoot);
copyfile(fullfile(packageRoot,"config"),fullfile(pointerPackageRoot,"config"));
copyfile(fullfile(packageRoot,"data"),fullfile(pointerPackageRoot,"data"));
copyfile(fullfile(packageRoot,"topology"),fullfile(pointerPackageRoot,"topology"));
triplens_ecms_vpp_simulate("PackageRoot",pointerPackageRoot, ...
    "TripTime",0.2,"StopTime",1.0);
pointerSecond = triplens_ecms_vpp_simulate("PackageRoot",pointerPackageRoot, ...
    "TripTime",0.2,"StopTime",1.0);
pointerText = strtrim(string(fileread(fullfile(pointerPackageRoot,"latest_run.txt"))));
expectedPointer = "runs/"+pointerSecond.RunId;
assert(pointerText==expectedPointer,"TripLens:PointerSelfTest", ...
    "latest_run.txt contains stale or concatenated bytes after replacement.");
assert(isfolder(fullfile(pointerPackageRoot,char(pointerText))), ...
    "TripLens:PointerSelfTest","latest_run.txt does not resolve to a run folder.");
checks(end+1) = "transactional latest-run pointer replacement";

report = struct("Passed",numel(checks),"Checks",checks, ...
    "RunIds",[normal.RunId;gridLoss.RunId;commandRun.RunId], ...
    "TemporaryRunsRemovedOnReturn",true);
fprintf("PASS: ECMS_SELF_TEST %d/%d checks passed.\n",numel(checks),numel(checks));
disp(checks);
end

function cleanupSelfTestFolder(pathValue)
if isfolder(pathValue)
    rmdir(pathValue,"s");
end
end
