#!/usr/bin/env python3
"""Add a physical LP-BFP operator-PB -> protection -> breaker chain to V36."""

from __future__ import annotations

import argparse
import re
import tempfile
from pathlib import Path


MARKER = "TRIPLENS_LP_BFP_OPERATOR_CHAIN_V1"


def replace_once(text: str, pattern: str, replacement: str, label: str) -> str:
    patched, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise ValueError(f"{label}: expected one semantic match, found {count}")
    return patched


def patch_text(source: str) -> str:
    if MARKER in source:
        return source
    if "TRIPLENS_OPCUA_RUN_DRIVEN_LIVE_V2" not in source:
        raise ValueError("verified RunDriven V2 marker is missing")

    declarations = (
        "  // TRIPLENS_LP_BFP_OPERATOR_CHAIN_V1\n"
        "  input Real vppLPFWPTripPushbuttonNative(start=0)\n"
        "    \"Operator LP BFP Trip pushbutton; external OPC UA input\";\n"
        "  input Real vppLPFWPResetPushbuttonNative(start=0)\n"
        "    \"Operator LP BFP reset pushbutton; external OPC UA input\";\n"
        "  output Real vppLPFWPTripCommandNative\n"
        "    \"LP BFP Trip command generated from operator pushbutton\";\n"
        "  output Real vppLPFWPTripLatchNative\n"
        "    \"Latched LP BFP protection state\";\n"
        "  output Real vppVCBA02TripCommandNative\n"
        "    \"VCB-A02 Trip command generated by the LP BFP Trip latch\";\n"
        "  discrete Real vppLPFWPTripLatchState(start=0, fixed=true)\n"
        "    \"Internal LP BFP Trip latch memory\";"
    )
    declaration_pattern = (
        r"^\s*output Real vppLPFWPTripCommandNative\([^;]*\);\s*\r?\n"
        r"\s*output Real vppLPFWPTripLatchNative\([^;]*\);\s*\r?\n"
        r"\s*output Real vppVCBA02TripCommandNative\([^;]*\);"
    )
    source = replace_once(
        source, declaration_pattern, declarations, "LP BFP declarations"
    )

    equations = (
        "  // TRIPLENS_LP_BFP_OPERATOR_CHAIN_V1: observable protection chain\n"
        "  vppLPFWPTripCommandNative =\n"
        "    if vppLPFWPTripPushbuttonNative >= 0.5 then 1 else 0;\n"
        "  vppLPFWPTripLatchNative = vppLPFWPTripLatchState;\n"
        "  vppVCBA02TripCommandNative = vppLPFWPTripLatchState;\n"
        "  when vppLPFWPResetPushbuttonNative >= 0.5 then\n"
        "    vppLPFWPTripLatchState = 0;\n"
        "  elsewhen vppLPFWPTripPushbuttonNative >= 0.5 then\n"
        "    vppLPFWPTripLatchState = 1;\n"
        "  end when;"
    )
    derivative_pattern = (
        r"^\s*der\(vppLPFWPTripCommandNative\)\s*=\s*[^;]+;\s*\r?\n"
        r"\s*der\(vppLPFWPTripLatchNative\)\s*=\s*[^;]+;\s*\r?\n"
        r"\s*der\(vppVCBA02TripCommandNative\)\s*=\s*[^;]+;"
    )
    source = replace_once(
        source, derivative_pattern, equations, "LP BFP placeholder equations"
    )

    # Two verified V36 families exist in the field.  The newer one has a
    # causal breaker-image state; the older Valve12 source publishes the
    # writable contact directly.  Patch exactly one of those semantic forms.
    applied_pattern = (
        r"(?P<head>der\(vppVCBA02ClosedApplied\)\s*=\s*\r?\n\s*)"
        r"\(vppVCBA02ClosedNative\s*-\s*vppVCBA02ClosedApplied\)"
    )
    if re.search(applied_pattern, source, flags=re.MULTILINE):
        source = replace_once(
            source,
            applied_pattern,
            (
                r"\g<head>((if vppVCBA02TripCommandNative >= 0.5 then 0 "
                r"else vppVCBA02ClosedNative) - vppVCBA02ClosedApplied)"
            ),
            "VCB-A02 applied-state protection equation",
        )
    else:
        published_pattern = (
            r"vppECMSVCBA02Closed\s*=\s*vppVCBA02ClosedNative\s*>=\s*0\.5\s+and\s+"
            r"vppECMSBusAAvailable\s*;"
        )
        source = replace_once(
            source,
            published_pattern,
            (
                "vppECMSVCBA02Closed = vppVCBA02TripCommandNative < 0.5 and "
                "vppVCBA02ClosedNative >= 0.5 and vppECMSBusAAvailable;"
            ),
            "VCB-A02 published protection equation",
        )
        source = replace_once(
            source,
            r"vppLPFWPMotorEnergized\s*=\s*vppVCBA02ClosedNative\s*>=\s*0\.5\s*;",
            "vppLPFWPMotorEnergized = vppECMSVCBA02Closed;",
            "LP BFP motor breaker binding",
        )

    for required in (
        "input Real vppLPFWPTripPushbuttonNative",
        "input Real vppLPFWPResetPushbuttonNative",
        "vppLPFWPTripLatchState = 1",
        "vppVCBA02TripCommandNative",
    ):
        if required not in source:
            raise ValueError(f"post-patch contract missing: {required}")
    if re.search(r"der\(vpp(?:LPFWPTripCommand|LPFWPTripLatch|VCBA02TripCommand)Native\)", source):
        raise ValueError("a legacy LP BFP placeholder derivative remains")
    return source


def write_atomic(path: Path, text: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", newline="", delete=False, dir=path.parent
    ) as stream:
        stream.write(text)
        temporary = Path(stream.name)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    args = parser.parse_args()
    original = args.source.read_text(encoding="utf-8-sig")
    patched = patch_text(original)
    write_atomic(args.source, patched)
    print(f"PASS: {MARKER}")
    print("Operator inputs: vppLPFWPTripPushbuttonNative, vppLPFWPResetPushbuttonNative")
    print("RAW chain: TRIP_CMD -> TRIP_LATCH -> VCB_TRIP_CMD -> VCB OPEN")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
