// Generated companion for config/equipment_drawing_master_v1.csv.
// Exact Equipment identity only: no fuzzy matching.
export const EQUIPMENT_DRAWING_MASTER=[
  {
    "equipment_id": "GT",
    "event_equipment": "GT",
    "aliases": "",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "GT",
    "ecms_page": "ECMS_VPP",
    "ecms_location_id": "GT",
    "detail_asset": "",
    "equipment_type": "SYSTEM",
    "mapping_status": "BOUND",
    "notes": "GT appears in both plant and ECMS overviews"
  },
  {
    "equipment_id": "52GT",
    "event_equipment": "52GT",
    "aliases": "GT BREAKER",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_VPP",
    "ecms_location_id": "52GT",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "Generator breaker is ECMS-only"
  },
  {
    "equipment_id": "ST",
    "event_equipment": "ST",
    "aliases": "STG",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_VPP",
    "ecms_location_id": "ST",
    "detail_asset": "",
    "equipment_type": "SYSTEM",
    "mapping_status": "BOUND",
    "notes": "ST generator visible on ECMS; no separate v36 Process View symbol"
  },
  {
    "equipment_id": "52ST",
    "event_equipment": "52ST",
    "aliases": "ST BREAKER",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_VPP",
    "ecms_location_id": "52ST",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "Generator breaker is ECMS-only"
  },
  {
    "equipment_id": "CB-IN-A",
    "event_equipment": "CB-IN-A",
    "aliases": "IN-A",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "CB-IN-A",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "BUS-A incoming breaker"
  },
  {
    "equipment_id": "CB-IN-B",
    "event_equipment": "CB-IN-B",
    "aliases": "IN-B",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "CB-IN-B",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "BUS-B incoming breaker"
  },
  {
    "equipment_id": "CB-TIE-AB",
    "event_equipment": "CB-TIE-AB",
    "aliases": "TIE-AB;BUS TIE",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "CB-TIE-AB",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "6.9 kV bus tie breaker"
  },
  {
    "equipment_id": "BUS-A",
    "event_equipment": "BUS-A",
    "aliases": "6.9KV BUS-A",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "BUS-A",
    "detail_asset": "",
    "equipment_type": "BUS",
    "mapping_status": "BOUND",
    "notes": "Auxiliary bus A"
  },
  {
    "equipment_id": "BUS-B",
    "event_equipment": "BUS-B",
    "aliases": "6.9KV BUS-B",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "BUS-B",
    "detail_asset": "",
    "equipment_type": "BUS",
    "mapping_status": "BOUND",
    "notes": "Auxiliary bus B"
  },
  {
    "equipment_id": "VCB-A01",
    "event_equipment": "VCB-A01",
    "aliases": "HP BFP FEEDER;FWP-HP VCB",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "VCB-A01",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "HP BFP feeder breaker"
  },
  {
    "equipment_id": "VCB-B01",
    "event_equipment": "VCB-B01",
    "aliases": "IP BFP FEEDER;FWP-IP VCB",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "VCB-B01",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "IP BFP feeder breaker"
  },
  {
    "equipment_id": "VCB-A02",
    "event_equipment": "VCB-A02",
    "aliases": "LP BFP FEEDER;FWP-LP VCB",
    "plant_page": "",
    "plant_location_id": "",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "VCB-A02",
    "detail_asset": "",
    "equipment_type": "BREAKER",
    "mapping_status": "BOUND",
    "notes": "LP BFP feeder breaker"
  },
  {
    "equipment_id": "FWP-HP",
    "event_equipment": "HP BFP",
    "aliases": "FWP-HP;HP FWP",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_BFP",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "VCB-A01",
    "detail_asset": "",
    "equipment_type": "PUMP",
    "mapping_status": "BOUND",
    "notes": "Plant pump location plus ECMS feeder location"
  },
  {
    "equipment_id": "FWP-HP-NRV",
    "event_equipment": "HP BFP NRV",
    "aliases": "HP FWP NRV;FWP-HP NRV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_BFP_NRV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/opcua/check_valves/hp-fwp-discharge-nrv.svg",
    "equipment_type": "CHECK_VALVE",
    "mapping_status": "BOUND",
    "notes": "HP BFP discharge NRV"
  },
  {
    "equipment_id": "FWP-IP",
    "event_equipment": "IP BFP",
    "aliases": "FWP-IP;IP FWP",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_BFP",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "VCB-B01",
    "detail_asset": "",
    "equipment_type": "PUMP",
    "mapping_status": "BOUND",
    "notes": "Plant pump location plus ECMS feeder location"
  },
  {
    "equipment_id": "FWP-IP-NRV",
    "event_equipment": "IP BFP NRV",
    "aliases": "IP FWP NRV;FWP-IP NRV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_BFP_NRV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/opcua/check_valves/ip-fwp-discharge-nrv.svg",
    "equipment_type": "CHECK_VALVE",
    "mapping_status": "BOUND",
    "notes": "IP BFP discharge NRV"
  },
  {
    "equipment_id": "FWP-LP",
    "event_equipment": "LP BFP",
    "aliases": "FWP-LP;LP FWP",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_BFP",
    "ecms_page": "ECMS_6P9KV",
    "ecms_location_id": "VCB-A02",
    "detail_asset": "",
    "equipment_type": "PUMP",
    "mapping_status": "BOUND",
    "notes": "Plant pump location plus ECMS feeder location"
  },
  {
    "equipment_id": "FWP-LP-NRV",
    "event_equipment": "LP BFP NRV",
    "aliases": "LP FWP NRV;FWP-LP NRV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_BFP_NRV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/opcua/check_valves/lp-fwp-discharge-nrv.svg",
    "equipment_type": "CHECK_VALVE",
    "mapping_status": "BOUND",
    "notes": "LP BFP discharge NRV"
  },
  {
    "equipment_id": "HP-FWCV",
    "event_equipment": "HP FWCV",
    "aliases": "HP_FWCV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_FWCV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/hp-fwcv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "HP drum feedwater control valve"
  },
  {
    "equipment_id": "HP-STM-VLV",
    "event_equipment": "HP STEAM VALVE",
    "aliases": "HP_STEAM_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_STEAM_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/hp-steam-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "HP drum steam valve"
  },
  {
    "equipment_id": "IP-FWCV",
    "event_equipment": "IP FWCV",
    "aliases": "IP_FWCV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_FWCV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/ip-fwcv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "IP drum feedwater control valve"
  },
  {
    "equipment_id": "IP-STM-VLV",
    "event_equipment": "IP STEAM VALVE",
    "aliases": "IP_STEAM_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_STEAM_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/ip-steam-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "IP drum steam valve"
  },
  {
    "equipment_id": "LP-STM-VLV",
    "event_equipment": "LP STEAM VALVE",
    "aliases": "LP_STEAM_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_STEAM_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/lp-steam-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "LP drum steam valve"
  },
  {
    "equipment_id": "LP-FW-VLV",
    "event_equipment": "LP FW VALVE",
    "aliases": "LP_FW_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_FW_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/lp-fw-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "LP drum feedwater valve"
  },
  {
    "equipment_id": "LP-HPIP-FW-VLV",
    "event_equipment": "LP TO HPIP FW VALVE",
    "aliases": "LP_TO_HPIP_FW_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_TO_HPIP_FW_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/lp-to-hpip-fw-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "LP to HP/IP feedwater valve"
  },
  {
    "equipment_id": "COND-EXT-VLV",
    "event_equipment": "COND EXTRACTION VALVE",
    "aliases": "COND_EXTRACTION_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "COND_EXTRACTION_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/cond-extraction-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "Condenser extraction control valve"
  },
  {
    "equipment_id": "HP-TURB-ADM-VLV",
    "event_equipment": "HP TURB ADM VALVE",
    "aliases": "HP_TURB_ADM_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_TURB_ADM_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/hp-turb-adm-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "HP turbine admission valve"
  },
  {
    "equipment_id": "HP-FW-ISO-VLV",
    "event_equipment": "HP FW ISO VALVE",
    "aliases": "HP_FW_ISO_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_FW_ISO_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/hp-fw-iso-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "HP BFP discharge isolation valve"
  },
  {
    "equipment_id": "IP-FW-ISO-VLV",
    "event_equipment": "IP FW ISO VALVE",
    "aliases": "IP_FW_ISO_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_FW_ISO_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/ip-fw-iso-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "IP BFP discharge isolation valve"
  },
  {
    "equipment_id": "IP-TURB-ADM-VLV",
    "event_equipment": "IP TURB ADM VALVE",
    "aliases": "IP_TURB_ADM_VLV",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_TURB_ADM_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "topology/valves/ip-turb-adm-vlv.svg",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "IP turbine admission valve"
  },
  {
    "equipment_id": "HP-FEEDWATER",
    "event_equipment": "HP FEEDWATER",
    "aliases": "HP FW",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_FEEDWATER",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "PROCESS_PATH",
    "mapping_status": "BOUND",
    "notes": "HP feedwater path"
  },
  {
    "equipment_id": "IP-FEEDWATER",
    "event_equipment": "IP FEEDWATER",
    "aliases": "IP FW",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_FEEDWATER",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "PROCESS_PATH",
    "mapping_status": "BOUND",
    "notes": "IP feedwater path"
  },
  {
    "equipment_id": "LP-FEEDWATER",
    "event_equipment": "LP FEEDWATER",
    "aliases": "LP FW",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_FEEDWATER",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "PROCESS_PATH",
    "mapping_status": "BOUND",
    "notes": "LP feedwater path"
  },
  {
    "equipment_id": "HP-DRUM",
    "event_equipment": "HP DRUM",
    "aliases": "HP_DRUM",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_DRUM",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VESSEL",
    "mapping_status": "BOUND",
    "notes": "HP HRSG drum"
  },
  {
    "equipment_id": "IP-DRUM",
    "event_equipment": "IP DRUM",
    "aliases": "IP_DRUM",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_DRUM",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VESSEL",
    "mapping_status": "BOUND",
    "notes": "IP HRSG drum"
  },
  {
    "equipment_id": "LP-DRUM",
    "event_equipment": "LP DRUM",
    "aliases": "LP_DRUM",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_DRUM",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VESSEL",
    "mapping_status": "BOUND",
    "notes": "LP HRSG drum"
  },
  {
    "equipment_id": "GT-EXHAUST",
    "event_equipment": "GT EXHAUST",
    "aliases": "GT_EXHAUST",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "GT_EXHAUST",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "PROCESS_PATH",
    "mapping_status": "BOUND",
    "notes": "GT exhaust into HRSG"
  },
  {
    "equipment_id": "HP-TURBINE",
    "event_equipment": "HP TURBINE",
    "aliases": "HP TURB",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_TURBINE",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "TURBINE",
    "mapping_status": "BOUND",
    "notes": "HP steam turbine"
  },
  {
    "equipment_id": "IP-TURBINE",
    "event_equipment": "IP TURBINE",
    "aliases": "IP TURB",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "IP_TURBINE",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "TURBINE",
    "mapping_status": "BOUND",
    "notes": "IP steam turbine"
  },
  {
    "equipment_id": "LP-TURBINE",
    "event_equipment": "LP TURBINE",
    "aliases": "LP TURB",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_TURBINE",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "TURBINE",
    "mapping_status": "BOUND",
    "notes": "LP steam turbine"
  },
  {
    "equipment_id": "GTG",
    "event_equipment": "GTG",
    "aliases": "GT GENERATOR",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "GTG",
    "ecms_page": "ECMS_VPP",
    "ecms_location_id": "GT",
    "detail_asset": "",
    "equipment_type": "SYSTEM",
    "mapping_status": "BOUND",
    "notes": "GT generator visible in v36 and ECMS"
  },
  {
    "equipment_id": "HP-BYPASS-VLV",
    "event_equipment": "HP Bypass",
    "aliases": "HP BYPASS;HP BYPASS VALVE",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_BYPASS_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "HP bypass symbol in v36"
  },
  {
    "equipment_id": "LP-BYPASS-VLV",
    "event_equipment": "LP Bypass",
    "aliases": "LP BYPASS;LP BYPASS VALVE",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_BYPASS_VLV",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "LP bypass symbol in v36"
  },
  {
    "equipment_id": "HP-SPRAY",
    "event_equipment": "HP Spray",
    "aliases": "HP SPRAY VALVE",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "HP_SPRAY",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "HP spray symbol in v36"
  },
  {
    "equipment_id": "LP-SPRAY",
    "event_equipment": "LP Spray",
    "aliases": "LP SPRAY VALVE",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "LP_SPRAY",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VALVE",
    "mapping_status": "BOUND",
    "notes": "LP spray symbol in v36"
  },
  {
    "equipment_id": "CONDENSER",
    "event_equipment": "Condenser",
    "aliases": "CONDENSER",
    "plant_page": "PLANT_OVERVIEW",
    "plant_location_id": "CONDENSER",
    "ecms_page": "",
    "ecms_location_id": "",
    "detail_asset": "",
    "equipment_type": "VESSEL",
    "mapping_status": "BOUND",
    "notes": "Condenser symbol in v36"
  }
];
const pairs=[];
for(const row of EQUIPMENT_DRAWING_MASTER){
  pairs.push([row.event_equipment,row]);
  pairs.push([row.equipment_id,row]);
  for(const alias of String(row.aliases||'').split(';').map(x=>x.trim()).filter(Boolean))pairs.push([alias,row]);
}
export const EQUIPMENT_DRAWING_INDEX=Object.freeze(Object.fromEntries(pairs));
export function resolveEquipmentDrawing(value){return EQUIPMENT_DRAWING_INDEX[String(value||'').trim()]||null;}
