// Generated from config/alarm_registry_v1.csv. Exact EVENT registry identity -> one drawing location.
// Do not fuzzy-match EVENT rows. Runtime EVENT rows may resolve by rule_id or exact equipment::tag.
export const EVENT_DRAWING_MAP=[
  {
    "rule_id": "GT_TRIP_LATCH",
    "event_class": "PROTECTION",
    "priority": "CRITICAL",
    "equipment": "GT",
    "tag": "TRIP_LATCH",
    "source_node": "vppGTTripLatch",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "GT TRIP LATCH ACTIVE",
    "return_message": "GT TRIP LATCH RESET",
    "enabled": "1",
    "delay_s": "0",
    "view": "vpp",
    "location_id": "GT",
    "group": "GT/ST 발전·차단기",
    "lookup_key": "GT::TRIP_LATCH"
  },
  {
    "rule_id": "GT_BREAKER_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "52GT",
    "tag": "BREAKER_OPEN",
    "source_node": "vpp52GTClosed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "52GT BREAKER OPEN",
    "return_message": "52GT BREAKER CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "vpp",
    "location_id": "GT",
    "group": "GT/ST 발전·차단기",
    "lookup_key": "52GT::BREAKER_OPEN"
  },
  {
    "rule_id": "ST_TRIP_LATCH",
    "event_class": "PROTECTION",
    "priority": "CRITICAL",
    "equipment": "ST",
    "tag": "TRIP_LATCH",
    "source_node": "vppSTTripLatchPublished",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "ST TRIP LATCH ACTIVE",
    "return_message": "ST TRIP LATCH RESET",
    "enabled": "1",
    "delay_s": "0",
    "view": "vpp",
    "location_id": "ST",
    "group": "GT/ST 발전·차단기",
    "lookup_key": "ST::TRIP_LATCH"
  },
  {
    "rule_id": "ST_BREAKER_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "52ST",
    "tag": "BREAKER_OPEN",
    "source_node": "vpp52STClosed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "52ST BREAKER OPEN",
    "return_message": "52ST BREAKER CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "vpp",
    "location_id": "ST",
    "group": "GT/ST 발전·차단기",
    "lookup_key": "52ST::BREAKER_OPEN"
  },
  {
    "rule_id": "CB_IN_A_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "CB-IN-A",
    "tag": "BREAKER_OPEN",
    "source_node": "vppECMSCBInAClosed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "CB-IN-A OPEN",
    "return_message": "CB-IN-A CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "CB-IN-A",
    "group": "6.9 kV 전기",
    "lookup_key": "CB-IN-A::BREAKER_OPEN"
  },
  {
    "rule_id": "CB_IN_B_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "CB-IN-B",
    "tag": "BREAKER_OPEN",
    "source_node": "vppECMSCBInBClosed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "CB-IN-B OPEN",
    "return_message": "CB-IN-B CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "CB-IN-B",
    "group": "6.9 kV 전기",
    "lookup_key": "CB-IN-B::BREAKER_OPEN"
  },
  {
    "rule_id": "CB_TIE_AB_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "CB-TIE-AB",
    "tag": "BREAKER_OPEN",
    "source_node": "vppECMSCBTieClosed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "CB-TIE-AB OPEN",
    "return_message": "CB-TIE-AB CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "CB-TIE-AB",
    "group": "6.9 kV 전기",
    "lookup_key": "CB-TIE-AB::BREAKER_OPEN"
  },
  {
    "rule_id": "BUS_A_UNAVAILABLE",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "BUS-A",
    "tag": "BUS_UNAVAILABLE",
    "source_node": "vppECMSBusAAvailable",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "BUS-A UNAVAILABLE",
    "return_message": "BUS-A AVAILABLE",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "BUS-A",
    "group": "6.9 kV 전기",
    "lookup_key": "BUS-A::BUS_UNAVAILABLE"
  },
  {
    "rule_id": "BUS_B_UNAVAILABLE",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "BUS-B",
    "tag": "BUS_UNAVAILABLE",
    "source_node": "vppECMSBusBAvailable",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "BUS-B UNAVAILABLE",
    "return_message": "BUS-B AVAILABLE",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "BUS-B",
    "group": "6.9 kV 전기",
    "lookup_key": "BUS-B::BUS_UNAVAILABLE"
  },
  {
    "rule_id": "VCB_A01_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "VCB-A01",
    "tag": "BREAKER_OPEN",
    "source_node": "vppECMSVCBA01Closed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "VCB-A01 OPEN",
    "return_message": "VCB-A01 CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "VCB-A01",
    "group": "6.9 kV 전기",
    "lookup_key": "VCB-A01::BREAKER_OPEN"
  },
  {
    "rule_id": "VCB_B01_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "VCB-B01",
    "tag": "BREAKER_OPEN",
    "source_node": "vppECMSVCBB01Closed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "VCB-B01 OPEN",
    "return_message": "VCB-B01 CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "VCB-B01",
    "group": "6.9 kV 전기",
    "lookup_key": "VCB-B01::BREAKER_OPEN"
  },
  {
    "rule_id": "VCB_A02_OPEN",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "VCB-A02",
    "tag": "BREAKER_OPEN",
    "source_node": "vppECMSVCBA02Closed",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "VCB-A02 OPEN",
    "return_message": "VCB-A02 CLOSED",
    "enabled": "1",
    "delay_s": "0",
    "view": "sld",
    "location_id": "VCB-A02",
    "group": "6.9 kV 전기",
    "lookup_key": "VCB-A02::BREAKER_OPEN"
  },
  {
    "rule_id": "HP_FWP_MOTOR_OFF",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "HP BFP",
    "tag": "MOTOR_DEENERGIZED",
    "source_node": "vppHPFWPMotorEnergized",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP BFP MOTOR DEENERGIZED",
    "return_message": "HP BFP MOTOR ENERGIZED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "HP_BFP",
    "group": "HP 급수",
    "lookup_key": "HP BFP::MOTOR_DEENERGIZED"
  },
  {
    "rule_id": "HP_FWP_RUNNING_LOST",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "HP BFP",
    "tag": "RUNNING_LOST",
    "source_node": "vppHPFWPRunning",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP BFP RUNNING LOST",
    "return_message": "HP BFP RUNNING RESTORED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "HP_BFP",
    "group": "HP 급수",
    "lookup_key": "HP BFP::RUNNING_LOST"
  },
  {
    "rule_id": "HP_FWP_SPEED_LOST",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "HP BFP",
    "tag": "SPEED_PROVEN_LOST",
    "source_node": "vppHPFWPSpeedProven",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP BFP SPEED PROVEN LOST",
    "return_message": "HP BFP SPEED PROVEN RESTORED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "HP_BFP",
    "group": "HP 급수",
    "lookup_key": "HP BFP::SPEED_PROVEN_LOST"
  },
  {
    "rule_id": "HP_FWP_NRV_CLOSED",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "HP BFP NRV",
    "tag": "CHECK_VALVE_CLOSED",
    "source_node": "vppHPFWPCheckValveOpen",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP BFP CHECK VALVE CLOSED",
    "return_message": "HP BFP CHECK VALVE OPEN",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "HP_BFP_NRV",
    "group": "HP 급수",
    "lookup_key": "HP BFP NRV::CHECK_VALVE_CLOSED"
  },
  {
    "rule_id": "IP_FWP_MOTOR_OFF",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "IP BFP",
    "tag": "MOTOR_DEENERGIZED",
    "source_node": "vppIPFWPMotorEnergized",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP BFP MOTOR DEENERGIZED",
    "return_message": "IP BFP MOTOR ENERGIZED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "IP_BFP",
    "group": "IP 급수",
    "lookup_key": "IP BFP::MOTOR_DEENERGIZED"
  },
  {
    "rule_id": "IP_FWP_RUNNING_LOST",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "IP BFP",
    "tag": "RUNNING_LOST",
    "source_node": "vppIPFWPRunning",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP BFP RUNNING LOST",
    "return_message": "IP BFP RUNNING RESTORED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "IP_BFP",
    "group": "IP 급수",
    "lookup_key": "IP BFP::RUNNING_LOST"
  },
  {
    "rule_id": "IP_FWP_SPEED_LOST",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "IP BFP",
    "tag": "SPEED_PROVEN_LOST",
    "source_node": "vppIPFWPSpeedProven",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP BFP SPEED PROVEN LOST",
    "return_message": "IP BFP SPEED PROVEN RESTORED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "IP_BFP",
    "group": "IP 급수",
    "lookup_key": "IP BFP::SPEED_PROVEN_LOST"
  },
  {
    "rule_id": "IP_FWP_NRV_CLOSED",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "IP BFP NRV",
    "tag": "CHECK_VALVE_CLOSED",
    "source_node": "vppIPFWPCheckValveOpen",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP BFP CHECK VALVE CLOSED",
    "return_message": "IP BFP CHECK VALVE OPEN",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "IP_BFP_NRV",
    "group": "IP 급수",
    "lookup_key": "IP BFP NRV::CHECK_VALVE_CLOSED"
  },
  {
    "rule_id": "LP_FWP_MOTOR_OFF",
    "event_class": "PROTECTION",
    "priority": "HIGH",
    "equipment": "LP BFP",
    "tag": "MOTOR_DEENERGIZED",
    "source_node": "vppLPFWPMotorEnergized",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "LP BFP MOTOR DEENERGIZED",
    "return_message": "LP BFP MOTOR ENERGIZED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "LP_BFP",
    "group": "LP 급수",
    "lookup_key": "LP BFP::MOTOR_DEENERGIZED"
  },
  {
    "rule_id": "LP_FWP_RUNNING_LOST",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "LP BFP",
    "tag": "RUNNING_LOST",
    "source_node": "vppLPFWPRunning",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "LP BFP RUNNING LOST",
    "return_message": "LP BFP RUNNING RESTORED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "LP_BFP",
    "group": "LP 급수",
    "lookup_key": "LP BFP::RUNNING_LOST"
  },
  {
    "rule_id": "LP_FWP_SPEED_LOST",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "LP BFP",
    "tag": "SPEED_PROVEN_LOST",
    "source_node": "vppLPFWPSpeedProven",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "LP BFP SPEED PROVEN LOST",
    "return_message": "LP BFP SPEED PROVEN RESTORED",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "LP_BFP",
    "group": "LP 급수",
    "lookup_key": "LP BFP::SPEED_PROVEN_LOST"
  },
  {
    "rule_id": "LP_FWP_NRV_CLOSED",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "LP BFP NRV",
    "tag": "CHECK_VALVE_CLOSED",
    "source_node": "vppLPFWPCheckValveOpen",
    "active_when": "LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "LP BFP CHECK VALVE CLOSED",
    "return_message": "LP BFP CHECK VALVE OPEN",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "LP_BFP_NRV",
    "group": "LP 급수",
    "lookup_key": "LP BFP NRV::CHECK_VALVE_CLOSED"
  },
  {
    "rule_id": "VLV_HP_FWCV_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "HP FWCV",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvHPFWCVFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP FWCV FAULT ACTIVE",
    "return_message": "HP FWCV FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "HP_FWCV",
    "group": "밸브/액추에이터",
    "lookup_key": "HP FWCV::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_HP_STEAM_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "HP STEAM VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvHPSteamFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP STEAM VALVE FAULT ACTIVE",
    "return_message": "HP STEAM VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "HP_STEAM_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "HP STEAM VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_IP_FWCV_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "IP FWCV",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvIPFWCVFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP FWCV FAULT ACTIVE",
    "return_message": "IP FWCV FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "IP_FWCV",
    "group": "밸브/액추에이터",
    "lookup_key": "IP FWCV::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_IP_STEAM_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "IP STEAM VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvIPSteamFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP STEAM VALVE FAULT ACTIVE",
    "return_message": "IP STEAM VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "IP_STEAM_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "IP STEAM VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_LP_STEAM_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "LP STEAM VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvLPSteamFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "LP STEAM VALVE FAULT ACTIVE",
    "return_message": "LP STEAM VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "LP_STEAM_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "LP STEAM VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_LP_FW_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "LP FW VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvLPFWFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "LP FW VALVE FAULT ACTIVE",
    "return_message": "LP FW VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "LP_FW_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "LP FW VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_LP_TO_HPIP_FW_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "LP TO HPIP FW VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvLPToHPIPFWFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "LP TO HPIP FW VALVE FAULT ACTIVE",
    "return_message": "LP TO HPIP FW VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "LP_TO_HPIP_FW_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "LP TO HPIP FW VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_COND_EXTRACTION_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "COND EXTRACTION VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvCondExtractionFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "COND EXTRACTION VALVE FAULT ACTIVE",
    "return_message": "COND EXTRACTION VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "COND_EXTRACTION_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "COND EXTRACTION VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_HP_TURB_ADM_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "HP TURB ADM VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvHPTurbAdmFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP TURB ADM VALVE FAULT ACTIVE",
    "return_message": "HP TURB ADM VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "HP_TURB_ADM_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "HP TURB ADM VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_HP_FW_ISO_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "HP FW ISO VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvHPFWIsoFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "HP FW ISO VALVE FAULT ACTIVE",
    "return_message": "HP FW ISO VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "HP_FW_ISO_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "HP FW ISO VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_IP_FW_ISO_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "IP FW ISO VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvIPFWIsoFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP FW ISO VALVE FAULT ACTIVE",
    "return_message": "IP FW ISO VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "IP_FW_ISO_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "IP FW ISO VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "VLV_IP_TURB_ADM_FAULT",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "IP TURB ADM VALVE",
    "tag": "VALVE_FAULT",
    "source_node": "vppVlvIPTurbAdmFaultActive",
    "active_when": "HIGH",
    "active_threshold": "0.5",
    "return_threshold": "0.5",
    "unit": "BOOL",
    "active_message": "IP TURB ADM VALVE FAULT ACTIVE",
    "return_message": "IP TURB ADM VALVE FAULT RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "valves",
    "location_id": "IP_TURB_ADM_VLV",
    "group": "밸브/액추에이터",
    "lookup_key": "IP TURB ADM VALVE::VALVE_FAULT"
  },
  {
    "rule_id": "HP_FW_FLOW_LOW",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "HP FEEDWATER",
    "tag": "FLOW_LOW",
    "source_node": "vppHPFWPMassFlowTH",
    "active_when": "BASELINE_RATIO_LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.6",
    "unit": "t/h",
    "active_message": "HP FW FLOW LOW ALARM",
    "return_message": "HP FW FLOW LOW RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "HP_FEEDWATER",
    "group": "HP 급수",
    "lookup_key": "HP FEEDWATER::FLOW_LOW"
  },
  {
    "rule_id": "IP_FW_FLOW_LOW",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "IP FEEDWATER",
    "tag": "FLOW_LOW",
    "source_node": "vppIPFWPMassFlowTH",
    "active_when": "BASELINE_RATIO_LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.6",
    "unit": "t/h",
    "active_message": "IP FW FLOW LOW ALARM",
    "return_message": "IP FW FLOW LOW RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "IP_FEEDWATER",
    "group": "IP 급수",
    "lookup_key": "IP FEEDWATER::FLOW_LOW"
  },
  {
    "rule_id": "LP_FW_FLOW_LOW",
    "event_class": "ALARM",
    "priority": "HIGH",
    "equipment": "LP FEEDWATER",
    "tag": "FLOW_LOW",
    "source_node": "vppLPFWPMassFlowTH",
    "active_when": "BASELINE_RATIO_LOW",
    "active_threshold": "0.5",
    "return_threshold": "0.6",
    "unit": "t/h",
    "active_message": "LP FW FLOW LOW ALARM",
    "return_message": "LP FW FLOW LOW RETURN",
    "enabled": "1",
    "delay_s": "0",
    "view": "event",
    "location_id": "LP_FEEDWATER",
    "group": "LP 급수",
    "lookup_key": "LP FEEDWATER::FLOW_LOW"
  },
  {
    "rule_id": "HP_DRUM_LEVEL_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "HP DRUM",
    "tag": "LEVEL_LOW",
    "source_node": "vppHPDrumLevelM",
    "active_when": "LOW",
    "active_threshold": "0.95",
    "return_threshold": "0.97",
    "unit": "m",
    "active_message": "HP DRUM LEVEL LOW ALARM",
    "return_message": "HP DRUM LEVEL LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "HP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "HP DRUM::LEVEL_LOW"
  },
  {
    "rule_id": "HP_DRUM_LEVEL_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "HP DRUM",
    "tag": "LEVEL_LOW_LOW",
    "source_node": "vppHPDrumLevelM",
    "active_when": "LOW",
    "active_threshold": "0.85",
    "return_threshold": "0.87",
    "unit": "m",
    "active_message": "HP DRUM LEVEL LOW-LOW ALARM",
    "return_message": "HP DRUM LEVEL LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "HP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "HP DRUM::LEVEL_LOW_LOW"
  },
  {
    "rule_id": "IP_DRUM_LEVEL_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "IP DRUM",
    "tag": "LEVEL_LOW",
    "source_node": "vppIPDrumLevelM",
    "active_when": "LOW",
    "active_threshold": "0.95",
    "return_threshold": "0.97",
    "unit": "m",
    "active_message": "IP DRUM LEVEL LOW ALARM",
    "return_message": "IP DRUM LEVEL LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "IP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "IP DRUM::LEVEL_LOW"
  },
  {
    "rule_id": "IP_DRUM_LEVEL_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "IP DRUM",
    "tag": "LEVEL_LOW_LOW",
    "source_node": "vppIPDrumLevelM",
    "active_when": "LOW",
    "active_threshold": "0.85",
    "return_threshold": "0.87",
    "unit": "m",
    "active_message": "IP DRUM LEVEL LOW-LOW ALARM",
    "return_message": "IP DRUM LEVEL LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "IP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "IP DRUM::LEVEL_LOW_LOW"
  },
  {
    "rule_id": "LP_DRUM_LEVEL_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "LP DRUM",
    "tag": "LEVEL_LOW",
    "source_node": "vppLPDrumLevelM",
    "active_when": "LOW",
    "active_threshold": "1.65",
    "return_threshold": "1.67",
    "unit": "m",
    "active_message": "LP DRUM LEVEL LOW ALARM",
    "return_message": "LP DRUM LEVEL LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "LP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "LP DRUM::LEVEL_LOW"
  },
  {
    "rule_id": "LP_DRUM_LEVEL_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "LP DRUM",
    "tag": "LEVEL_LOW_LOW",
    "source_node": "vppLPDrumLevelM",
    "active_when": "LOW",
    "active_threshold": "1.55",
    "return_threshold": "1.57",
    "unit": "m",
    "active_message": "LP DRUM LEVEL LOW-LOW ALARM",
    "return_message": "LP DRUM LEVEL LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "LP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "LP DRUM::LEVEL_LOW_LOW"
  },
  {
    "rule_id": "GT_EXHAUST_FLOW_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "GT EXHAUST",
    "tag": "FLOW_LOW",
    "source_node": "vppGTExhaustMassFlowTH",
    "active_when": "LOW",
    "active_threshold": "1962",
    "return_threshold": "1983.6",
    "unit": "t/h",
    "active_message": "GT EXHAUST FLOW LOW ALARM",
    "return_message": "GT EXHAUST FLOW LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "GT_EXHAUST",
    "group": "GT 배기",
    "lookup_key": "GT EXHAUST::FLOW_LOW"
  },
  {
    "rule_id": "GT_EXHAUST_FLOW_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "GT EXHAUST",
    "tag": "FLOW_LOW_LOW",
    "source_node": "vppGTExhaustMassFlowTH",
    "active_when": "LOW",
    "active_threshold": "1080",
    "return_threshold": "1101.6",
    "unit": "t/h",
    "active_message": "GT EXHAUST FLOW LOW-LOW ALARM",
    "return_message": "GT EXHAUST FLOW LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "GT_EXHAUST",
    "group": "GT 배기",
    "lookup_key": "GT EXHAUST::FLOW_LOW_LOW"
  },
  {
    "rule_id": "GT_EXHAUST_TEMP_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "GT EXHAUST",
    "tag": "TEMPERATURE_LOW",
    "source_node": "vppGTExhaustTemperatureK",
    "active_when": "LOW",
    "active_threshold": "805",
    "return_threshold": "810",
    "unit": "K",
    "active_message": "GT EXHAUST TEMPERATURE LOW ALARM",
    "return_message": "GT EXHAUST TEMPERATURE LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "GT_EXHAUST",
    "group": "GT 배기",
    "lookup_key": "GT EXHAUST::TEMPERATURE_LOW"
  },
  {
    "rule_id": "GT_EXHAUST_TEMP_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "GT EXHAUST",
    "tag": "TEMPERATURE_LOW_LOW",
    "source_node": "vppGTExhaustTemperatureK",
    "active_when": "LOW",
    "active_threshold": "580",
    "return_threshold": "585",
    "unit": "K",
    "active_message": "GT EXHAUST TEMPERATURE LOW-LOW ALARM",
    "return_message": "GT EXHAUST TEMPERATURE LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "GT_EXHAUST",
    "group": "GT 배기",
    "lookup_key": "GT EXHAUST::TEMPERATURE_LOW_LOW"
  },
  {
    "rule_id": "HP_DRUM_LEVEL_HIGH",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "HP DRUM",
    "tag": "LEVEL_HIGH",
    "source_node": "vppHPDrumLevelM",
    "active_when": "HIGH",
    "active_threshold": "1.15",
    "return_threshold": "1.13",
    "unit": "m",
    "active_message": "HP DRUM LEVEL HIGH ALARM",
    "return_message": "HP DRUM LEVEL HIGH RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "HP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "HP DRUM::LEVEL_HIGH"
  },
  {
    "rule_id": "HP_DRUM_LEVEL_HIGH_HIGH",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "HP DRUM",
    "tag": "LEVEL_HIGH_HIGH",
    "source_node": "vppHPDrumLevelM",
    "active_when": "HIGH",
    "active_threshold": "1.25",
    "return_threshold": "1.23",
    "unit": "m",
    "active_message": "HP DRUM LEVEL HIGH-HIGH ALARM",
    "return_message": "HP DRUM LEVEL HIGH-HIGH RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "HP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "HP DRUM::LEVEL_HIGH_HIGH"
  },
  {
    "rule_id": "IP_DRUM_LEVEL_HIGH",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "IP DRUM",
    "tag": "LEVEL_HIGH",
    "source_node": "vppIPDrumLevelM",
    "active_when": "HIGH",
    "active_threshold": "1.15",
    "return_threshold": "1.13",
    "unit": "m",
    "active_message": "IP DRUM LEVEL HIGH ALARM",
    "return_message": "IP DRUM LEVEL HIGH RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "IP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "IP DRUM::LEVEL_HIGH"
  },
  {
    "rule_id": "IP_DRUM_LEVEL_HIGH_HIGH",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "IP DRUM",
    "tag": "LEVEL_HIGH_HIGH",
    "source_node": "vppIPDrumLevelM",
    "active_when": "HIGH",
    "active_threshold": "1.25",
    "return_threshold": "1.23",
    "unit": "m",
    "active_message": "IP DRUM LEVEL HIGH-HIGH ALARM",
    "return_message": "IP DRUM LEVEL HIGH-HIGH RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "IP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "IP DRUM::LEVEL_HIGH_HIGH"
  },
  {
    "rule_id": "LP_DRUM_LEVEL_HIGH",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "LP DRUM",
    "tag": "LEVEL_HIGH",
    "source_node": "vppLPDrumLevelM",
    "active_when": "HIGH",
    "active_threshold": "1.85",
    "return_threshold": "1.83",
    "unit": "m",
    "active_message": "LP DRUM LEVEL HIGH ALARM",
    "return_message": "LP DRUM LEVEL HIGH RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "LP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "LP DRUM::LEVEL_HIGH"
  },
  {
    "rule_id": "LP_DRUM_LEVEL_HIGH_HIGH",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "LP DRUM",
    "tag": "LEVEL_HIGH_HIGH",
    "source_node": "vppLPDrumLevelM",
    "active_when": "HIGH",
    "active_threshold": "1.95",
    "return_threshold": "1.93",
    "unit": "m",
    "active_message": "LP DRUM LEVEL HIGH-HIGH ALARM",
    "return_message": "LP DRUM LEVEL HIGH-HIGH RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "LP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "LP DRUM::LEVEL_HIGH_HIGH"
  },
  {
    "rule_id": "HP_DRUM_PRESSURE_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "HP DRUM",
    "tag": "PRESSURE_LOW",
    "source_node": "vppHPDrumPressurePa",
    "active_when": "LOW",
    "active_threshold": "12000000",
    "return_threshold": "12200000",
    "unit": "Pa",
    "active_message": "HP DRUM PRESSURE LOW ALARM",
    "return_message": "HP DRUM PRESSURE LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "HP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "HP DRUM::PRESSURE_LOW"
  },
  {
    "rule_id": "HP_DRUM_PRESSURE_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "HP DRUM",
    "tag": "PRESSURE_LOW_LOW",
    "source_node": "vppHPDrumPressurePa",
    "active_when": "LOW",
    "active_threshold": "10800000",
    "return_threshold": "11000000",
    "unit": "Pa",
    "active_message": "HP DRUM PRESSURE LOW-LOW ALARM",
    "return_message": "HP DRUM PRESSURE LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "HP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "HP DRUM::PRESSURE_LOW_LOW"
  },
  {
    "rule_id": "IP_DRUM_PRESSURE_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "IP DRUM",
    "tag": "PRESSURE_LOW",
    "source_node": "vppIPDrumPressurePa",
    "active_when": "LOW",
    "active_threshold": "2550000",
    "return_threshold": "2600000",
    "unit": "Pa",
    "active_message": "IP DRUM PRESSURE LOW ALARM",
    "return_message": "IP DRUM PRESSURE LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "IP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "IP DRUM::PRESSURE_LOW"
  },
  {
    "rule_id": "IP_DRUM_PRESSURE_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "IP DRUM",
    "tag": "PRESSURE_LOW_LOW",
    "source_node": "vppIPDrumPressurePa",
    "active_when": "LOW",
    "active_threshold": "2300000",
    "return_threshold": "2350000",
    "unit": "Pa",
    "active_message": "IP DRUM PRESSURE LOW-LOW ALARM",
    "return_message": "IP DRUM PRESSURE LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "IP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "IP DRUM::PRESSURE_LOW_LOW"
  },
  {
    "rule_id": "LP_DRUM_PRESSURE_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "LP DRUM",
    "tag": "PRESSURE_LOW",
    "source_node": "vppLPDrumPressurePa",
    "active_when": "LOW",
    "active_threshold": "500000",
    "return_threshold": "510000",
    "unit": "Pa",
    "active_message": "LP DRUM PRESSURE LOW ALARM",
    "return_message": "LP DRUM PRESSURE LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "LP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "LP DRUM::PRESSURE_LOW"
  },
  {
    "rule_id": "LP_DRUM_PRESSURE_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "LP DRUM",
    "tag": "PRESSURE_LOW_LOW",
    "source_node": "vppLPDrumPressurePa",
    "active_when": "LOW",
    "active_threshold": "450000",
    "return_threshold": "460000",
    "unit": "Pa",
    "active_message": "LP DRUM PRESSURE LOW-LOW ALARM",
    "return_message": "LP DRUM PRESSURE LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.5",
    "view": "event",
    "location_id": "LP_DRUM",
    "group": "HRSG Drum",
    "lookup_key": "LP DRUM::PRESSURE_LOW_LOW"
  },
  {
    "rule_id": "HP_STEAM_FLOW_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "HP TURBINE",
    "tag": "FLOW_LOW",
    "source_node": "vppHPTurbineSteamFlowTH",
    "active_when": "LOW",
    "active_threshold": "486",
    "return_threshold": "496.8",
    "unit": "t/h",
    "active_message": "HP TURBINE STEAM FLOW LOW ALARM",
    "return_message": "HP TURBINE STEAM FLOW LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "HP_TURBINE",
    "group": "Steam Turbine",
    "lookup_key": "HP TURBINE::FLOW_LOW"
  },
  {
    "rule_id": "HP_STEAM_FLOW_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "HP TURBINE",
    "tag": "FLOW_LOW_LOW",
    "source_node": "vppHPTurbineSteamFlowTH",
    "active_when": "LOW",
    "active_threshold": "324",
    "return_threshold": "334.8",
    "unit": "t/h",
    "active_message": "HP TURBINE STEAM FLOW LOW-LOW ALARM",
    "return_message": "HP TURBINE STEAM FLOW LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "HP_TURBINE",
    "group": "Steam Turbine",
    "lookup_key": "HP TURBINE::FLOW_LOW_LOW"
  },
  {
    "rule_id": "IP_STEAM_FLOW_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "IP TURBINE",
    "tag": "FLOW_LOW",
    "source_node": "vppIPTurbineSteamFlowTH",
    "active_when": "LOW",
    "active_threshold": "576",
    "return_threshold": "586.8",
    "unit": "t/h",
    "active_message": "IP TURBINE STEAM FLOW LOW ALARM",
    "return_message": "IP TURBINE STEAM FLOW LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "IP_TURBINE",
    "group": "Steam Turbine",
    "lookup_key": "IP TURBINE::FLOW_LOW"
  },
  {
    "rule_id": "IP_STEAM_FLOW_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "IP TURBINE",
    "tag": "FLOW_LOW_LOW",
    "source_node": "vppIPTurbineSteamFlowTH",
    "active_when": "LOW",
    "active_threshold": "378",
    "return_threshold": "388.8",
    "unit": "t/h",
    "active_message": "IP TURBINE STEAM FLOW LOW-LOW ALARM",
    "return_message": "IP TURBINE STEAM FLOW LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "IP_TURBINE",
    "group": "Steam Turbine",
    "lookup_key": "IP TURBINE::FLOW_LOW_LOW"
  },
  {
    "rule_id": "LP_STEAM_FLOW_LOW",
    "event_class": "ALARM",
    "priority": "MEDIUM",
    "equipment": "LP TURBINE",
    "tag": "FLOW_LOW",
    "source_node": "vppLPTurbineSteamFlowTH",
    "active_when": "LOW",
    "active_threshold": "630",
    "return_threshold": "640.8",
    "unit": "t/h",
    "active_message": "LP TURBINE STEAM FLOW LOW ALARM",
    "return_message": "LP TURBINE STEAM FLOW LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "LP_TURBINE",
    "group": "Steam Turbine",
    "lookup_key": "LP TURBINE::FLOW_LOW"
  },
  {
    "rule_id": "LP_STEAM_FLOW_LOW_LOW",
    "event_class": "ALARM",
    "priority": "CRITICAL",
    "equipment": "LP TURBINE",
    "tag": "FLOW_LOW_LOW",
    "source_node": "vppLPTurbineSteamFlowTH",
    "active_when": "LOW",
    "active_threshold": "424.8",
    "return_threshold": "435.6",
    "unit": "t/h",
    "active_message": "LP TURBINE STEAM FLOW LOW-LOW ALARM",
    "return_message": "LP TURBINE STEAM FLOW LOW-LOW RETURN",
    "enabled": "1",
    "delay_s": "0.2",
    "view": "event",
    "location_id": "LP_TURBINE",
    "group": "Steam Turbine",
    "lookup_key": "LP TURBINE::FLOW_LOW_LOW"
  }
];
export const EVENT_DRAWING_BY_RULE=Object.freeze(Object.fromEntries(EVENT_DRAWING_MAP.map(x=>[x.rule_id,x])));
export const EVENT_DRAWING_BY_LOOKUP=Object.freeze(Object.fromEntries(EVENT_DRAWING_MAP.map(x=>[x.lookup_key,x])));
export function resolveEventDrawing(event={}){
  const rule=String(event.rule_id||'').trim();
  if(rule&&EVENT_DRAWING_BY_RULE[rule])return EVENT_DRAWING_BY_RULE[rule];
  const key=`${String(event.equipment||'').trim()}::${String(event.tag||'').trim()}`;
  return EVENT_DRAWING_BY_LOOKUP[key]||null;
}
