setCommandLineOptions("--std=3.4");
loadModel(Modelica, {"3.2.3"});
getErrorString();
loadFile("/workspace/vendor/ThermoSysPro/ThermoSysPro/package.mo");
getErrorString();
loadFile("/workspace/build/TripLens_CombinedCycle_BFPTrip.mo");
getErrorString();
cd("/workspace/build");
simulate(
  TripLens_CombinedCycle_BFPTrip,
  startTime=0,
  stopTime=@STOP_TIME@,
  numberOfIntervals=@NUMBER_OF_INTERVALS@,
  tolerance=1e-3,
  method="dassl",
  outputFormat="csv",
  simflags="-noEventEmit",
  fileNamePrefix="thermosyspro_bfp_blind",
  variableFilter="^(time|PompeAlimHP\\.(Vr|Wm|R|deltaP)|arretPomesHP\\.y\\.signal|Alternateur\\.Welec|Ballon(HP|MP|BP)\\.(yLevel\\.signal|zl|P)|vanne_alimentation(HP|MP|BP)\\.Ouv\\.signal|Temperature\\.y\\.signal|vpp(GTExhaustMassFlowTH|HPTurbineSteamFlowTH|IPTurbineSteamFlowTH|LPTurbineSteamFlowTH|FWPHPMassFlowTH))$");
getErrorString();
